### ISSUE TITLE
could not build wheels for pyrangelibc-danieldugas

### ISSUE THREAD

**Issue by XinZhengLXp** [leekwoon/nav-gym#7]
when i pip install -e . ，i  got this problem. 
this is my system version.
but when i install this package in base enviroment ,i can install it successfully.
![屏幕截图 2024-04-24 193502](https://github.com/leekwoon/nav-gym/assets/148566651/a1d6cc7d-9bc9-45f2-b418-ebb6cb2b7c67)

 Building wheel for pyrangelibc-danieldugas (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/lhq/venv/hrlnav/bin/python3.6 /home/lhq/venv/hrlnav/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmp4pw3atxj
       cwd: /tmp/pip-install-eb74ucql/pyrangelibc-danieldugas_531b0a2e792f42bab54e6c3f0ef2e4f7
  Complete output (76 lines):
  Compiling without CUDA support. To enable CUDA use:
     $ sudo WITH_CUDA=ON python setup.py install
  Compiling without trace enabled for Bresenham's Line
     $ sudo TRACE=ON python setup.py install
  
  --------------
  
  running bdist_wheel
  running build
  running build_ext
  /tmp/pip-build-env-1s7f_cdo/overlay/lib/python3.6/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-eb74ucql/pyrangelibc-danieldugas_531b0a2e792f42bab54e6c3f0ef2e4f7/pywrapper/RangeLibc.pyx
    tree = Parsing.p_module(s, pxd, full_module_name)
  
  Error compiling Cython file:
  ------------------------------------------------------------
  ...
                      for x in range(width):
                          self.thisptr.grid[x][y] = <bool>arg1[y,x]
              else:
                  self.thisptr = new OMap(arg1)
          else:
              print "Failed to construct PyOMap, check argument types."
                    ^
  ------------------------------------------------------------
  
  pywrapper/RangeLibc.pyx:134:18: Syntax error in simple statement list
  Compiling ./pywrapper/RangeLibc.pyx because it changed.
  [1/1] Cythonizing ./pywrapper/RangeLibc.pyx
  Traceback (most recent call last):
    File "/home/lhq/venv/hrlnav/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/home/lhq/venv/hrlnav/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/lhq/venv/hrlnav/lib/python3.6/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 262, in build_wheel
      metadata_directory)
    File "/tmp/pip-build-env-1s7f_cdo/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 231, in build_wheel
      wheel_directory, config_settings)
    File "/tmp/pip-build-env-1s7f_cdo/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-1s7f_cdo/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 194, in <module>
      cmdclass = {'build_ext': build_ext})
    File "/tmp/pip-build-env-1s7f_cdo/overlay/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-1s7f_cdo/overlay/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "/tmp/pip-build-env-1s7f_cdo/overlay/lib/python3.6/site-packages/Cython/Distutils/build_ext.py", line 131, in build_extension
      ext,force=self.force, quiet=self.verbose == 0, **options
    File "/tmp/pip-build-env-1s7f_cdo/overlay/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
      cythonize_one(*args)
    File "/tmp/pip-build-env-1s7f_cdo/overlay/lib/python3.6/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
      raise CompileError(None, pyx_file)
  Cython.Compiler.Errors.CompileError: ./pywrapper/RangeLibc.pyx
  ----------------------------------------
  ERROR: Failed building wheel for pyrangelibc-danieldugas
Failed to build pyrangelibc-danieldugas
ERROR: Could not build wheels for pyrangelibc-danieldugas, which is required to install pyproject.toml-based projects

**Comment by leekwoon** [comment]
@XinZhengLXp  I think you can check https://github.com/leekwoon/hrl-nav/issues/2#issuecomment-1888427058.

**Comment by darlingbenke** [comment]
解决了吗，我也遇到同样的问题

**Comment by leekwoon** [comment]
Hi, @darlingbenke 

You can check out https://github.com/leekwoon/hrl-nav/issues/2#issuecomment-1888427058.

 Just change some files of range_libc to make it work in python 3.x.
 
 e.g., print "..." --> print("...")
